# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='comentario',
            new_name='blog_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='has_blog',
            field=models.BooleanField(default=False),
        ),
    ]
