# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160925_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='has_blog',
            new_name='visible_blog',
        ),
    ]
